markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Lincoln Clarete
url: http://clarete.li
description: A fantastic blog that is fantastic.
twitter: lincolnclarete
github: clarete
gravatar_url: http://www.gravatar.com/avatar/da48f488ae92ee21bef65e83d77d8544.png
